### ISSUE TITLE
[MSC]: Issue Comment Created - Delete Comment WF

### ISSUE THREAD

**Issue by user-lfdsystems** [lfdsystems/workflows#33]

**Comment by developer-lfdsystems** [comment]
Need more Information.

Reason:
This is a good reason.

**Comment by developer-lfdsystems** [comment]
Need more Information.

Reason:
This is a good reason.

**Comment by developer-lfdsystems** [comment]
Need more Information.

Reason:
This is a good reason.

**Comment by developer-lfdsystems** [comment]
Need more Information.

Reason:
This is a good reason.

**Comment by developer-lfdsystems** [comment]
Need more Information.

Reason:
This is a good reason.

**Comment by user-lfdsystems** [comment]
@seniordev-lfdsystems,

Kindly review.

**Comment by user-lfdsystems** [comment]
This worked as expected.
